src/apps/company/urls.py
from django.urls import path
from .views import CreateJobCallView,CompanyJobCallsView,JobCallDetailsView
urlpatterns = [
    path('create_jobcall', CreateJobCallView.as_view(), name='company.create_jobcall'),
    path('', CompanyJobCallsView.as_view(), name='company.jobcalls'),
    path('details/<int:pk>/', JobCallDetailsView.as_view(), name='article-detail'),
]

src/core/urls.py
from django.urls import path,include


urlpatterns = [

    path('accounts', include('apps.accounts.urls')),
    path('', include('apps.jobcall.urls')),
    path('sessions/', include('apps.custom_session.urls')),
    path('company/', include('apps.company.urls')),
    path('aspirant/', include('apps.aspirant.urls')),
    path('api/', include('apps.apis.urls')),

]

src/apps/jobcall/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from apps.accounts.models import User
# Create your models here.


class JobCall(models.Model):
    OPEN =1
    CLOSED= 2
    FINISHED = 3
    STATES = (
        (OPEN, 'open'),
        (CLOSED, 'close'),
        (FINISHED, 'finished'),
    )
    closing_date = models.DateTimeField(_("closing date"))
    position = models.CharField(_("position"),max_length=150)
    description = models.TextField(_("description"))
    state = models.PositiveSmallIntegerField(choices=STATES,default=OPEN,verbose_name = _("state"))
    company = models.ForeignKey(User,verbose_name=_("company"),on_delete=models.CASCADE)
    aspirants = models.ManyToManyField(User,verbose_name=_("aspirants"),blank=True,related_name="jobcall_aspirant")
    @property
    def is_open(self):
        return self.state  == self.OPEN
    

    class Meta:
        order_with_respect_to = 'closing_date'
        verbose_name = _('job call')
        verbose_name_plural = _('job calls')

class AnonymousInscription(models.Model):
    full_name = models.CharField(_("full name"),max_length=150)
    jobcall = models.ForeignKey(JobCall,on_delete=models.CASCADE,verbose_name=_("anonymous aspirants"),blank=True)
    curriculum = models.FileField(upload_to='jobcall/curriculums',verbose_name=_("curriculum"))
    #file = pk.pdf

src/apps/company/forms.py
from django.utils.timezone import datetime #important if using timezones
from django import forms
from apps.jobcall.models import JobCall


class CreateJobCallForm(forms.ModelForm):
    class Meta:
        model = JobCall
        fields = ('position','description','closing_date','state')
        widgets = {
            'closing_date': forms.DateInput(format='%Y-%m-%d',
            attrs={'class': 'form_datetime','type':'date','min':datetime.today().strftime("%Y-%m-%d")}),
           
        }
    def save(self, commit=True): 
        return super().save(commit=commit)

src/apps/company/views.py
from django.views.generic import CreateView,View,DetailView
from django.contrib.auth import get_user_model
from django.utils.decorators import method_decorator
from django.shortcuts import render

from .forms import CreateJobCallForm
from apps.jobcall.models import JobCall
from apps.custom_session.decorators import role_required

User = get_user_model()
# Create your views here.
@method_decorator(role_required(rol=User.COMPANY),name="dispatch")
class CreateJobCallView(CreateView):
  
    form_class = CreateJobCallForm
    template_name = 'company/create_jobcall.html'
    success_url = '/company'
    def form_valid(self, form):
        #form.instance.jobcall = JobCall.objects.get(pk=self.kwargs['jobcall_id'])
        form.instance.company = self.request.user
        return super().form_valid(form)
  
@method_decorator(role_required(rol=User.COMPANY),name="dispatch")
class CompanyJobCallsView(View):
  def get(self, request): 
    context = {
    'jobcalls': JobCall.objects.filter(company__id=request.user.id).order_by('closing_date'),
    }
    return render(request, 'jobcall/list_jobcalls.html', context=context)

  def post(self, request):
    pass

  def push(self, request):
    pass
  def apply(self,jobcall):
    print(jobcall)

@method_decorator(role_required(rol=User.COMPANY),name="dispatch")
class JobCallDetailsView(DetailView):
  model = JobCall
  template_name = 'company/jobcall_details.html'
  queryset = JobCall.objects.all()

src/apps/company/templates/company/create_jobcall.html
{% extends 'jobcall/jobcall.master.html' %}

{% block content %}
{{form.errors}}
<div class="row">
  <div class="col-12">
    <h3 class="border-bottom border-gray pb-2 mb-0">Write a post</h3>
    <form method="POST" enctype="multipart/form-data" class="mt-3">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" value="Create" class="btn btn-primary" />
    </form>
  </div>
</div>
{% endblock %}

src/apps/company/templates/company/jobcall_details.html
{% extends 'jobcall/jobcall.master.html' %}

{% block content %}
{{form.errors}}
  <div class="col-12">
    <h3 class="border-bottom border-gray pb-2 mb-0">Write a post</h3>
    <form method="POST" enctype="multipart/form-data" class="mt-3">
      {% csrf_token %}
      <div class="card-body">
        <h5 class="card-title">{{ object.position }}</h5>
        <p class="card-text text-muted">{{ jobcall.description }}</p>
        <p class="card-text"><small class="text-muted">Company: {{object.company.first_name}}</small></p>
        {% if   object.is_open %}
        <p class="card-text"><small class="text-danger"> Closing date: {{object.closing_date}}</small></p>
        {% else %}
        <p class="card-text"><small class="text-muted"> Closed at: {{object.closing_date}}</small></p>
        {% endif %}
        <button type="button" class="list-group-item list-group-item-action active">Aspirants</button>
        <table class="table">            
        {% for aspirant in object.aspirants.all %}
          <tr>
            <th scope="row"></th>
            <td>{{aspirant.first_name}}</td>
            <td>{{aspirant.email}}</td>
          </tr>
        {% endfor %}    
        </table>       
        <button type="button" class="list-group-item list-group-item-action active">Anonymous Aspirants</button>
        <table class="table">            
        {% for aspirant in object.anonymousinscription_set.all %}
          <tr>
            <th scope="row"></th>
            <td>{{aspirant.full_name}}</td>
            <td>{{aspirant.curriculum}}</td>
          </tr>
        {% endfor %}    
        </table>        
       </div>
    </form>
  </div>
{% endblock %}